import type { IncidentCase, SceneHotspot } from "./types";

export const CASES: IncidentCase[] = [
  {
    id: "missed-recycle",
    title: "Recycling cart still full on collection day",
    neighborhood: "Temescal",
    location: "Telegraph near 49th",
    body: "It is 4 p.m. on the published recycling day. A residential blue cart is still at the curb, full, with no collection tag visible. Compost and trash carts on the same block are empty.",
    options: [
      { id: "cws", label: "California Waste Solutions (residential recycling)" },
      { id: "wm", label: "Waste Management (trash & compost)" },
      { id: "oak311", label: "Oakland 311 / Public Works" },
      { id: "stopwaste", label: "StopWaste / HHW" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "cws",
    explain:
      "CWS is the exclusive residential recycling collector in Oakland. A missed recycling cart is a CWS service issue, not WM and not 311 — unless the cart is blocking the sidewalk as a public-right-of-way condition.",
    known: ["Recycling day has passed", "Recycling cart still present", "Other carts on the block appear collected"],
    unknown: ["Whether the cart was out by 6 a.m.", "Whether a contamination tag was issued", "Whether access was blocked"],
  },
  {
    id: "overflow-dumpster",
    title: "Commercial dumpster overflowing into the alley",
    neighborhood: "KONO",
    location: "Telegraph & 35th alley",
    body: "A shared commercial dumpster is overflowing. Bags are on the ground. The enclosure gate is off its hinge. This has been true for two weeks.",
    options: [
      { id: "wm", label: "Waste Management (increase service / collection)" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311 if public ROW is obstructed" },
      { id: "stopwaste", label: "StopWaste" },
      { id: "property", label: "Property owner / manager (adequate service)" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "property",
    explain:
      "First pathway is the property: they must subscribe to adequate service and keep the enclosure usable. WM handles collection if service exists. 311 is appropriate if the overflow occupies the public right-of-way. STREETS documents the condition; it does not assign blame.",
    known: ["Overflow is present", "Enclosure is damaged", "Condition has persisted"],
    unknown: ["Current service level", "Who last overfilled it", "Whether a hauler missed a pickup"],
  },
  {
    id: "mattress",
    title: "Mattress on the sidewalk",
    neighborhood: "East Oakland",
    location: "98th Avenue near International",
    body: "A mattress is on the sidewalk beside an apartment building. No appointment tag. Pedestrians are walking in the street to get around it.",
    options: [
      { id: "wm", label: "Schedule WM bulky service (if it is a lawful set-out)" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311 — sidewalk obstruction / possible dumping" },
      { id: "stopwaste", label: "StopWaste" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "oak311",
    explain:
      "A mattress on the sidewalk with no verified bulky appointment is a public-right-of-way condition. 311 is the reporting channel. Residents can also schedule bulky service at 1-888-WM-BULKY. Placing items more than one day before a bulky appointment can be fined. Do not assume a tenant dumped it.",
    known: ["Mattress is on the sidewalk", "It obstructs the pedestrian path", "No appointment tag is visible"],
    unknown: ["Origin", "Whether a bulky appointment exists", "How long it has been there"],
  },
  {
    id: "paint",
    title: "Open paint cans by a litter bin",
    neighborhood: "West Oakland",
    location: "7th & Mandela",
    body: "Three open latex paint cans sit beside a City litter receptacle. Residue is on the pavement.",
    options: [
      { id: "wm", label: "Waste Management" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311 for the abandoned material" },
      { id: "stopwaste", label: "StopWaste / Alameda County HHW" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "oak311",
    explain:
      "Abandoned paint on the public way is a 311 condition and a hazard. Proper disposal of household paint is Alameda County HHW (1-800-606-6606; Oakland facility 2100 East 7th Street). STREETS trainees: observe → document → distance → refer. Do not handle.",
    known: ["Paint is present on public space", "Cans are open"],
    unknown: ["Who left it", "Whether it is still liquid", "Whether it is oil-based"],
  },
  {
    id: "batteries-cart",
    title: "Resident asking where household batteries go",
    neighborhood: "Fruitvale",
    location: "A residential kitchen",
    body: "A resident has a bag of AA, AAA, and a laptop battery. They want to put them in recycling “because metal.”",
    options: [
      { id: "wm", label: "Waste Management trash cart" },
      { id: "cws", label: "CWS battery collection / HHW" },
      { id: "oak311", label: "Oakland 311" },
      { id: "stopwaste", label: "Alameda County HHW facility" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "cws",
    explain:
      "CWS provides Oakland residential recycling and household battery collection. Lithium and rechargeable batteries are also accepted at County HHW facilities. They must never go in recycling, compost, or trash carts — fire risk.",
    known: ["Household batteries are present", "Resident intends to use a cart"],
    unknown: ["Whether CWS bag-on-cart instructions are current — confirm on CalWaste / Oakland Recycles"],
  },
  {
    id: "food-recovery",
    title: "Grocery with surplus prepared food",
    neighborhood: "Chinatown",
    location: "A covered food-generating market",
    body: "A grocery regularly discards unsold prepared foods in the compost. A manager asks if that satisfies SB 1383.",
    options: [
      { id: "wm", label: "Just use the compost service" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311" },
      { id: "stopwaste", label: "StopWaste — edible food recovery / ORRO" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Food recovery organization" },
    ],
    correct: "stopwaste",
    explain:
      "Covered food generators must recover surplus edible food for people, with a written agreement and monthly pound records. Composting inedible scraps is still required — but composting is not a substitute for edible-food recovery. StopWaste enforces ORRO.",
    known: ["Surplus edible food is being generated", "It is currently going to compost"],
    unknown: ["Whether the business is a Tier 1 or Tier 2 generator", "Whether a recovery agreement exists"],
  },
  {
    id: "oil",
    title: "Used motor oil in a garage",
    neighborhood: "Deep East Oakland",
    location: "A single-family driveway",
    body: "A resident changed oil and has two gallons in a milk jug.",
    options: [
      { id: "wm", label: "Pour it in trash" },
      { id: "cws", label: "CWS used-oil collection (residential)" },
      { id: "oak311", label: "Oakland 311" },
      { id: "stopwaste", label: "HHW facility also accepts automotive fluids" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "cws",
    explain:
      "CWS collects used motor oil and filters from Oakland residences. HHW facilities also take automotive fluids. Never pour oil in trash, compost, storm drains, or soil. A milk jug is not an approved long-term container — use a sealed original container or purpose-built oil jug.",
    known: ["Used oil is present", "It is currently in a milk jug"],
    unknown: ["Whether CWS pickup rules require a specific jug — confirm before setting out"],
  },
  {
    id: "construction",
    title: "Broken concrete and drywall at the curb",
    neighborhood: "Uptown",
    location: "27th Street",
    body: "A remodel has left concrete chunks and painted drywall at the curb. No bulky appointment tag.",
    options: [
      { id: "wm", label: "WM bulky (limited C&D; dirt/rock/concrete often excluded or extra)" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311 if dumped on public ROW" },
      { id: "stopwaste", label: "StopWaste" },
      { id: "property", label: "Property owner — C&D debris box" },
      { id: "other", label: "Licensed C&D facility" },
    ],
    correct: "property",
    explain:
      "Construction debris is the generator’s responsibility. Dirt, rock, and concrete are not standard bulky. Unscheduled curb piles on the public way are 311 conditions. Document what is there; do not assume a contractor “was supposed to take it.”",
    known: ["C&D material is at the curb", "No appointment tag visible"],
    unknown: ["Permit status", "Whether a debris box was ordered", "Who generated it"],
  },
  {
    id: "contamination-notice",
    title: "Recycling cart tagged for contamination",
    neighborhood: "Adams Point",
    location: "A 12-unit building",
    body: "Tenants find a contamination notice. The cart contains plastic bags of bottles plus a pizza box with food.",
    options: [
      { id: "wm", label: "Waste Management" },
      { id: "cws", label: "CWS — recycling quality; then property education" },
      { id: "oak311", label: "Oakland 311" },
      { id: "stopwaste", label: "StopWaste education resources" },
      { id: "property", label: "Property manager must educate and inspect" },
      { id: "other", label: "Another specialized service" },
    ],
    correct: "property",
    explain:
      "CWS issues the contamination finding on residential recycling. The property still has ORRO duties: indoor paired containers, annual education, periodic inspection and feedback. Bagged recyclables are treated as trash. Food in recycling ruins the load.",
    known: ["A contamination tag is present", "Bags and food are visible in recycling"],
    unknown: ["Whether this is a first or repeat tag", "Whether indoor stations exist"],
  },
  {
    id: "sharps",
    title: "Loose syringes near a bus stop",
    neighborhood: "Downtown",
    location: "14th & Broadway",
    body: "Two uncapped syringes are visible in the gutter next to a bus shelter. People are waiting for the 1 bus.",
    options: [
      { id: "wm", label: "Waste Management" },
      { id: "cws", label: "California Waste Solutions" },
      { id: "oak311", label: "Oakland 311 / Public Works needle response" },
      { id: "stopwaste", label: "HHW (for household sharps disposal, not street pickup)" },
      { id: "property", label: "Property management" },
      { id: "other", label: "Emergency services if an active injury" },
    ],
    correct: "oak311",
    explain:
      "Street sharps are a public-works / 311 safety condition. Do not pick them up with bare hands. Households dispose of their own sharps through authorized take-back, not carts. If someone is injured, that is emergency services — 911 — not STREETS.",
    known: ["Sharps are in the public way", "People are present"],
    unknown: ["How long they have been there", "Whether a needle-response crew is already assigned"],
  },
];

export const CASE_MAP = Object.fromEntries(CASES.map((c) => [c.id, c]));

export const DUMPSTER_SCENE: SceneHotspot[] = [
  {
    id: "bag-in-recycle",
    label: "Plastic bags stuffed with bottles",
    x: 18,
    y: 42,
    issue: "contamination",
    explain: "Bagged recyclables are treated as trash at the MRF. Place items loose.",
  },
  {
    id: "overflow",
    label: "Dumpster overflowing",
    x: 48,
    y: 38,
    issue: "overflow",
    explain: "Overflow is a service-capacity problem, not “extra trash.” Document volume and whether the public way is occupied.",
  },
  {
    id: "sofa",
    label: "Sofa beside the enclosure",
    x: 72,
    y: 55,
    issue: "dumping",
    explain: "A bulky item next to a dumpster is not automatically collection. It may be illegal dumping or an unscheduled bulky set-out. Do not assume who put it there.",
  },
  {
    id: "oil",
    label: "Sealed drum with oil markings",
    x: 62,
    y: 28,
    issue: "hazard",
    explain: "Automotive fluids are hazardous. Maintain distance. Do not open. Route to 311 if abandoned; HHW if a household is disposing of its own oil.",
  },
  {
    id: "sidewalk",
    label: "Bags blocking the sidewalk",
    x: 36,
    y: 70,
    issue: "access",
    explain: "This is an accessibility obstruction. Disabled residents, strollers, and transit riders are forced into the street.",
  },
  {
    id: "cart-ok",
    label: "Closed, upright residential carts",
    x: 10,
    y: 68,
    issue: "ok",
    explain: "Legitimate collection carts, lids closed, on the property side of the sidewalk — this is a normal set-out, not a condition.",
  },
];

export const SOFA_RECORD = {
  id: "sofa-35th",
  title: "Sofa beside an apartment building",
  location: "35th & Telegraph · KONO",
  body: "A fabric sofa sits on the sidewalk against a 24-unit building. No bulky tag. One cushion is wet. A dumpster enclosure is 15 feet away, closed, not overflowing.",
  question: "What do you actually know?",
  options: [
    { id: "A", label: "The tenant dumped it illegally." },
    { id: "B", label: "WM failed to collect it." },
    { id: "C", label: "The landlord abandoned it." },
    { id: "D", label: "A bulky item is present; origin and service status remain unverified." },
  ],
  correct: "D",
  explain:
    "STREETS documents conditions, not assumptions. You can see a sofa on the sidewalk. You cannot see who placed it, whether a bulky appointment exists, or whether a hauler missed it. Record what is known. Label what is uncertain. Then route: 311 for ROW obstruction; WM bulky if a resident is trying to dispose lawfully.",
};
