import type { SimCondition } from "./types";

export const SIM_META = {
  title: "98th Avenue exercise",
  location: "98th Avenue near International Blvd · East Oakland",
  intro:
    "You are standing on a simulated Oakland block. Identify every condition. Assign a waste stream where one applies. Flag hazards. Route the first pathway. Separate verified facts from inferences. Score a STREETS severity. Passing score is 80 of 100.",
};

export const SIM_CONDITIONS: SimCondition[] = [
  {
    id: "overflow",
    label: "Overflowing commercial dumpster",
    x: 22,
    y: 40,
    stream: "trash",
    hazard: false,
    pathway: "property",
    severity: 2,
    classify: "overflow / service-capacity",
    facts: ["Dumpster is over the rim", "Bags are on the ground around it"],
    inferences: ["The hauler skipped this stop", "The restaurant is the only generator"],
  },
  {
    id: "cardboard",
    label: "Flattened cardboard beside recycling",
    x: 38,
    y: 48,
    stream: "recycle",
    hazard: false,
    pathway: "cws",
    severity: 1,
    classify: "extra recycling set-out (may be legitimate)",
    facts: ["Flattened cardboard is stacked beside a recycling container"],
    inferences: ["This is illegal dumping", "CWS will refuse it"],
  },
  {
    id: "mattress",
    label: "Mattress on the sidewalk",
    x: 58,
    y: 62,
    stream: "special",
    hazard: false,
    pathway: "oak311",
    severity: 2,
    classify: "bulky item in public right-of-way",
    facts: ["A mattress occupies the sidewalk", "No appointment tag is visible"],
    inferences: ["A tenant dumped it last night", "WM missed a bulky pickup"],
  },
  {
    id: "tv",
    label: "Abandoned television",
    x: 70,
    y: 36,
    stream: "special",
    hazard: true,
    pathway: "oak311",
    severity: 2,
    classify: "abandoned e-waste",
    facts: ["A CRT/flat-panel TV is on the curb", "It is not inside a cart"],
    inferences: ["It still works", "Someone intended it as donation"],
  },
  {
    id: "bag-compost",
    label: "Plastic bag inside compost",
    x: 14,
    y: 58,
    stream: "trash",
    hazard: false,
    pathway: "property",
    severity: 1,
    classify: "contamination (compost)",
    facts: ["A plastic bag is visible in the compost container"],
    inferences: ["The whole load will be landfilled today", "A particular tenant did this"],
  },
  {
    id: "food",
    label: "Food waste on the pavement",
    x: 46,
    y: 72,
    stream: "compost",
    hazard: false,
    pathway: "oak311",
    severity: 1,
    classify: "scattered organics / litter",
    facts: ["Food scraps are on the pavement outside any cart"],
    inferences: ["Animals dragged it from the dumpster", "It is from the restaurant next door"],
  },
  {
    id: "path",
    label: "Blocked wheelchair path",
    x: 80,
    y: 68,
    stream: "none",
    hazard: true,
    pathway: "oak311",
    severity: 3,
    classify: "accessibility obstruction",
    facts: ["The sidewalk path of travel is not passable", "A wheelchair user would be forced into the street"],
    inferences: ["The City has already been notified", "This is only a code-enforcement issue, not a safety issue"],
  },
  {
    id: "cnd",
    label: "Construction debris pile",
    x: 86,
    y: 42,
    stream: "special",
    hazard: true,
    pathway: "property",
    severity: 2,
    classify: "C&D / possible dumping",
    facts: ["Broken board, drywall, and aggregate are stacked at the curb"],
    inferences: ["A permitted job is in progress", "This is household trash"],
  },
  {
    id: "carts",
    label: "Legitimate collection carts",
    x: 8,
    y: 36,
    stream: "none",
    hazard: false,
    pathway: "wm",
    severity: 0,
    classify: "normal set-out (not a defect)",
    facts: ["Carts are upright with lids closed on collection day"],
    inferences: ["They are contaminated inside", "They have been there all week"],
  },
  {
    id: "litter",
    label: "Ordinary pedestrian litter",
    x: 32,
    y: 78,
    stream: "trash",
    hazard: false,
    pathway: "oak311",
    severity: 1,
    classify: "scattered litter",
    facts: ["Small wrappers and cups are on the gutter"],
    inferences: ["A particular business is responsible", "This is illegal dumping of bulky waste"],
  },
];

export const SIM_WEIGHTS = {
  classification: 25,
  disposal: 20,
  safety: 15,
  routing: 15,
  documentation: 15,
  evidence: 10,
} as const;
