import type { SortItem, Stream } from "./types";

const recycleWrong = {
  compost: "Clean paper, metal, glass, and plastic containers belong in recycling — not compost. Compost is for food, food-soiled paper, and plant debris.",
  trash: "This is recoverable. Oakland recycling takes clean, empty, dry bottles, jugs, tubs, cans, foil, glass, and paper.",
  special: "This does not need hazardous-waste handling. Place it loose in the recycling cart.",
};

const compostWrong = {
  recycle: "Food and food-soiled paper contaminate recycling. They belong in Oakland compost.",
  trash: "Organics in landfill generate methane. Oakland compost takes food (including meat and dairy), food-soiled paper, and plant debris.",
  special: "This is ordinary organic material, not household hazardous waste.",
};

const trashWrong = {
  recycle: "This item jams sorting equipment, contaminates the load, or is not a bottle/jug/tub/can/jar/paper grade Oakland accepts.",
  compost: "Oakland compost does not accept plastic, compostable plastic, pet waste, diapers, or plastic-lined paper.",
  special: "This is residual trash, not a hazardous or specialty stream.",
};

const specialWrong = {
  recycle: "Hazardous and specialty items can start fires, leak, or injure workers. Never put them in recycling.",
  compost: "Hazardous material in compost contaminates soil amendments. Do not improvise.",
  trash: "Some residual waste belongs in trash — but batteries, chemicals, lamps, and electronics need authorized drop-off.",
};

export const ITEMS: SortItem[] = [
  {
    id: "alum-can",
    name: "Aluminum soda can",
    alt: "Empty aluminum beverage can",
    stream: "recycle",
    hint: "Empty and dry.",
    icon: "can",
    why: { recycle: "Metal cans are a core Oakland recycling grade. Empty and dry; place loose in the cart.", ...recycleWrong },
  },
  {
    id: "newspaper",
    name: "Newspaper",
    alt: "Folded newspaper",
    stream: "recycle",
    hint: "Clean and dry paper.",
    icon: "paper",
    why: { recycle: "Clean paper and newspaper belong in recycling.", ...recycleWrong },
  },
  {
    id: "cardboard",
    name: "Flattened shipping box",
    alt: "Flattened cardboard box",
    stream: "recycle",
    hint: "Flatten. Keep dry. Cut down if larger than 3 ft.",
    icon: "paper",
    why: {
      recycle: "Flatten cardboard. Extra flattened cardboard can sit beside the cart. Wet or greasy cardboard may go to compost instead.",
      ...recycleWrong,
    },
  },
  {
    id: "glass-jar",
    name: "Glass pasta-sauce jar",
    alt: "Empty glass food jar",
    stream: "recycle",
    hint: "Scrape food out. Lids can usually stay on.",
    icon: "glass",
    why: { recycle: "Glass bottles and jars are recyclable in Oakland. Empty them first.", ...recycleWrong },
  },
  {
    id: "plastic-jug",
    name: "Plastic milk jug",
    alt: "Empty HDPE plastic milk jug",
    stream: "recycle",
    hint: "Bottles, jugs, and tubs — by shape, not by the chasing-arrows number.",
    icon: "bottle",
    why: {
      recycle: "Oakland recycles plastic by shape: bottles, jugs, and tubs. Do not recycle by resin number.",
      ...recycleWrong,
    },
  },
  {
    id: "yogurt-tub",
    name: "Yogurt tub",
    alt: "Empty plastic yogurt tub",
    stream: "recycle",
    hint: "Scrape clean. Tubs are accepted.",
    icon: "bottle",
    why: { recycle: "Plastic tubs (yogurt, margarine) are accepted. Scrape food out first.", ...recycleWrong },
  },
  {
    id: "foil",
    name: "Clean aluminum foil",
    alt: "Ball of clean aluminum foil",
    stream: "recycle",
    hint: "Clean foil and trays. Ball small pieces together.",
    icon: "can",
    why: { recycle: "Clean aluminum foil and trays are metal recycling. Heavily food-soiled foil can go in trash.", ...recycleWrong },
  },
  {
    id: "mail",
    name: "Junk mail and envelopes",
    alt: "Stack of envelopes and mail",
    stream: "recycle",
    hint: "Window envelopes are fine.",
    icon: "paper",
    why: { recycle: "Clean mail and envelopes go in recycling.", ...recycleWrong },
  },
  {
    id: "banana",
    name: "Banana peel",
    alt: "Banana peel",
    stream: "compost",
    hint: "All food scraps, including peels.",
    icon: "food",
    why: { compost: "Fruit scraps are compost. They generate methane if landfilled.", ...compostWrong },
  },
  {
    id: "bones",
    name: "Chicken bones",
    alt: "Cooked chicken bones",
    stream: "compost",
    hint: "Oakland compost accepts meat and bones.",
    icon: "food",
    why: {
      compost: "Unlike backyard piles, Oakland’s municipal compost accepts meat, bones, dairy, and eggs.",
      ...compostWrong,
    },
  },
  {
    id: "pizza-box",
    name: "Greasy pizza box",
    alt: "Pizza box with grease stains",
    stream: "compost",
    hint: "Grease is the reason it leaves recycling.",
    icon: "paper",
    why: {
      compost: "Food-soiled paper — greasy pizza boxes, napkins — belongs in compost, not recycling.",
      recycle: "Grease contaminates paper recycling. Compost it.",
      trash: "This is recoverable organics. Compost it.",
      special: "Not hazardous.",
    },
  },
  {
    id: "napkin",
    name: "Used paper napkin",
    alt: "Crumpled paper napkin",
    stream: "compost",
    hint: "Food-soiled paper.",
    icon: "paper",
    why: { compost: "Napkins and paper towels are compost, not recycling.", ...compostWrong },
  },
  {
    id: "grounds",
    name: "Coffee grounds",
    alt: "Used coffee grounds",
    stream: "compost",
    hint: "Grounds and paper filters both compost.",
    icon: "food",
    why: { compost: "Coffee grounds and paper filters are compost.", ...compostWrong },
  },
  {
    id: "leaves",
    name: "Yard leaves",
    alt: "Pile of dry leaves",
    stream: "compost",
    hint: "Plant debris is compost. No dirt, rocks, or sod.",
    icon: "food",
    why: { compost: "Leaves, grass, flowers, and branches are compost.", ...compostWrong },
  },
  {
    id: "chopsticks",
    name: "Wooden chopsticks",
    alt: "Pair of untreated wooden chopsticks",
    stream: "compost",
    hint: "Untreated wood stirrers and chopsticks only.",
    icon: "wood",
    why: {
      compost: "Untreated single-use wood — chopsticks, stirrers, popsicle sticks — can go in Oakland compost.",
      ...compostWrong,
    },
  },
  {
    id: "plastic-bag",
    name: "Plastic grocery bag",
    alt: "Crumpled plastic film bag",
    stream: "trash",
    hint: "Film plastic jams sorting screens. Never bag recyclables.",
    icon: "bag",
    why: {
      trash: "Plastic bags and film are not Oakland curbside recycling. They wrap around equipment. Trash, or store for retailer take-back if available.",
      recycle: "Bags are a primary contaminant. They jam the Material Recovery Facility.",
      compost: "Even bags labeled compostable are not accepted in Oakland compost.",
      special: "Ordinary film is trash, not HHW.",
    },
  },
  {
    id: "styrofoam",
    name: "Polystyrene cup",
    alt: "White foam cup",
    stream: "trash",
    hint: "No curbside foam recycling in Oakland.",
    icon: "foam",
    why: { trash: "Polystyrene foam goes in trash in Oakland.", ...trashWrong },
  },
  {
    id: "diaper",
    name: "Used diaper",
    alt: "Rolled disposable diaper",
    stream: "trash",
    hint: "Never compost or recycle.",
    icon: "bag",
    why: {
      trash: "Diapers are trash. They contaminate compost and recycling.",
      ...trashWrong,
    },
  },
  {
    id: "chip-bag",
    name: "Chip bag",
    alt: "Metallized snack bag",
    stream: "trash",
    hint: "Mixed-material film.",
    icon: "bag",
    why: { trash: "Metallized snack bags are mixed material. Trash.", ...trashWrong },
  },
  {
    id: "utensils",
    name: "Disposable plastic fork",
    alt: "Single-use plastic fork",
    stream: "trash",
    hint: "Utensils are not bottles, jugs, or tubs.",
    icon: "bag",
    why: {
      trash: "Oakland recycles plastic by shape. Utensils, straws, and lids are not accepted shapes.",
      ...trashWrong,
    },
  },
  {
    id: "pla-cup",
    name: "Cup labeled “compostable”",
    alt: "PLA bioplastic cup with compostable label",
    stream: "trash",
    hint: "A compostable label is not an Oakland compost ticket.",
    icon: "cup",
    why: {
      trash: "PLA and compostable plastic foodware are not accepted in Oakland compost. They go in trash.",
      compost: "Oakland’s compost system cannot process compostable plastics. Label ≠ local acceptance.",
      recycle: "PLA is not a bottle/jug/tub grade and contaminates PET.",
      special: "Not hazardous — just residual.",
    },
  },
  {
    id: "pet-waste",
    name: "Bagged pet waste",
    alt: "Tied bag of pet waste",
    stream: "trash",
    hint: "Never compost.",
    icon: "bag",
    why: {
      trash: "Pet waste is trash in Oakland. It does not belong in compost.",
      compost: "Pet waste is a compost contaminant and a public-health issue.",
      recycle: "Never.",
      special: "Ordinary pet waste is trash, not HHW.",
    },
  },
  {
    id: "hose",
    name: "Garden hose",
    alt: "Coiled rubber garden hose",
    stream: "trash",
    hint: "Tanglers destroy sorting equipment.",
    icon: "tangler",
    why: {
      trash: "Hoses, ropes, and hangers are tanglers. Keep them out of recycling. Trash or reuse.",
      recycle: "Tanglers wrap around screens and can shut down a MRF.",
      compost: "Not organic.",
      special: "Not hazardous unless it contained chemicals.",
    },
  },
  {
    id: "milk-carton",
    name: "Milk carton",
    alt: "Empty plastic-lined milk carton",
    stream: "recycle",
    hint: "Cartons recycle. They do not compost.",
    icon: "carton",
    why: {
      recycle: "Oakland recycling accepts milk and juice cartons. Empty them. They are plastic-lined, so they are not compost.",
      compost: "Plastic-lined paper — milk cartons, most coffee cups — is not Oakland compost.",
      trash: "Empty cartons are recyclable.",
      special: "Not hazardous.",
    },
  },
  {
    id: "battery",
    name: "Lithium battery",
    alt: "Small lithium-ion cell",
    stream: "special",
    hint: "Fire risk. Never any cart.",
    icon: "battery",
    why: {
      special: "Batteries cause facility fires. Take household batteries to CWS collection or an Alameda County HHW facility. Do not put them in any cart.",
      ...specialWrong,
    },
  },
  {
    id: "cfl",
    name: "Fluorescent bulb",
    alt: "Compact fluorescent light bulb",
    stream: "special",
    hint: "Contains mercury.",
    icon: "bulb",
    why: {
      special: "Fluorescent lamps contain mercury. HHW drop-off only — Oakland facility at 2100 East 7th Street.",
      ...specialWrong,
    },
  },
  {
    id: "paint",
    name: "Latex paint can",
    alt: "Partially full paint can",
    stream: "special",
    hint: "Paint is household hazardous waste, even latex.",
    icon: "paint",
    why: {
      special: "Paint, stains, and thinners go to HHW. Do not put liquid paint in trash.",
      ...specialWrong,
    },
  },
  {
    id: "phone",
    name: "Broken smartphone",
    alt: "Cracked smartphone",
    stream: "special",
    hint: "E-waste. Not bulky dumping.",
    icon: "device",
    why: {
      special: "Electronics are e-waste. HHW facilities accept them. An abandoned TV on a sidewalk is a dumping condition, not a recycling cart item.",
      ...specialWrong,
    },
  },
  {
    id: "straw",
    name: "Plastic straw",
    alt: "Single-use plastic straw",
    stream: "trash",
    hint: "Not a recyclable shape.",
    icon: "bag",
    why: { trash: "Straws are trash in Oakland curbside.", ...trashWrong },
  },
  {
    id: "hanger",
    name: "Wire clothes hanger",
    alt: "Wire clothes hanger",
    stream: "trash",
    hint: "Tangler. Return to a dry cleaner when possible.",
    icon: "tangler",
    why: {
      trash: "Hangers are tanglers. Do not recycle curbside. Reuse or trash.",
      recycle: "Hangers wrap around equipment.",
      compost: "Not organic.",
      special: "Not HHW.",
    },
  },
  {
    id: "tea-bag",
    name: "Paper tea bag",
    alt: "Used paper tea bag",
    stream: "compost",
    hint: "Paper tea bags and filters. Skip plastic pyramid bags.",
    icon: "food",
    why: { compost: "Paper tea bags and coffee filters are compost. Plastic mesh bags are trash.", ...compostWrong },
  },
  {
    id: "lined-cup",
    name: "Plastic-lined coffee cup",
    alt: "Disposable coffee cup with plastic lining",
    stream: "trash",
    hint: "Most hot cups are plastic-lined.",
    icon: "cup",
    why: {
      trash: "Plastic-lined paper cups are not Oakland compost and are not a reliable recycling grade. Trash unless a specific local program says otherwise.",
      compost: "Plastic-lined cups are listed as not accepted in Oakland compost.",
      recycle: "Most lined cups are not bottles/jugs/tubs and fail paper mills.",
      special: "Not hazardous.",
    },
  },
  {
    id: "needles",
    name: "Used sharps",
    alt: "Syringe with needle",
    stream: "special",
    hint: "Never loose in any container.",
    icon: "device",
    why: {
      special: "Sharps go in a puncture-resistant container, then to an authorized take-back. Never recycling, compost, or loose trash. STREETS rule: observe, document, distance, refer.",
      ...specialWrong,
    },
  },
];

export const ITEM_MAP = Object.fromEntries(ITEMS.map((i) => [i.id, i]));

export function itemsById(ids: string[]): SortItem[] {
  return ids.map((id) => {
    const item = ITEM_MAP[id];
    if (!item) throw new Error(`Unknown sort item: ${id}`);
    return item;
  });
}

export const PRETEST_IDS = [
  "alum-can",
  "banana",
  "plastic-bag",
  "battery",
  "pizza-box",
  "pla-cup",
  "yogurt-tub",
  "diaper",
  "milk-carton",
  "hose",
];

export const MODULE2_IDS = [
  "newspaper",
  "cardboard",
  "alum-can",
  "glass-jar",
  "plastic-jug",
  "yogurt-tub",
  "foil",
  "mail",
  "plastic-bag",
  "styrofoam",
  "utensils",
  "diaper",
  "pet-waste",
  "pizza-box",
  "hose",
  "hanger",
  "chip-bag",
  "straw",
  "banana",
  "bones",
  "pla-cup",
  "lined-cup",
  "battery",
  "phone",
  "needles",
];

export const LANDFILL_IDS = [
  "plastic-bag",
  "pla-cup",
  "lined-cup",
  "chip-bag",
  "styrofoam",
  "utensils",
  "straw",
  "diaper",
  "pet-waste",
  "hose",
  "hanger",
  "milk-carton",
  "pizza-box",
  "foil",
  "chopsticks",
];

export const STREAM_META: Record<
  Stream,
  { label: string; short: string; instruction: string }
> = {
  recycle: {
    label: "Recycle",
    short: "Blue / recycling",
    instruction: "Clean. Empty. Dry. Loose in the cart — never bagged.",
  },
  compost: {
    label: "Compost",
    short: "Green / organics",
    instruction: "Food, food-soiled paper, plants. No plastic. No “compostable” plastic.",
  },
  trash: {
    label: "Trash",
    short: "Residual",
    instruction: "Only after reuse, recycle, compost, and special disposal are all no.",
  },
  special: {
    label: "Special disposal",
    short: "HHW / e-waste / bulky",
    instruction: "Do not improvise. Authorized drop-off or scheduled bulky service.",
  },
};
