const crypto = require('crypto');
function hashPhone(phone, salt = process.env.CONTACT_HASH_SALT || 'streets-dev-salt') { if (!phone) return null; return crypto.createHash('sha256').update(`${salt}:${String(phone).trim()}`).digest('hex'); }
function classifyIssueType(message = '') { const text = message.toLowerCase(); if (/(dump|trash|illegal dump)/.test(text)) return 'dumping'; if (/(graffiti|tagging)/.test(text)) return 'graffiti'; if (/(needle|human waste|biohazard|feces)/.test(text)) return 'biohazard'; if (/(wheelchair|ada|blocked sidewalk|access ramp)/.test(text)) return 'ada_obstruction'; if (/(streetlight|lighting|dark|unsafe)/.test(text)) return 'lighting_safety'; if (/(smoke|air quality|fumes)/.test(text)) return 'air_quality'; if (/(flood|water|drain|sewage)/.test(text)) return 'water_flooding'; if (/(encampment|sanitation)/.test(text)) return 'encampment_adjacent_sanitation'; return 'other_needs_review'; }
function classifySeverity(message = '') { const text = message.toLowerCase(); if (/(fire|shooting|stab|assault|overdose|medical emergency|immediate danger)/.test(text)) return 'emergency_referral'; if (/(needle|human waste|hazardous|blocked sidewalk|traffic danger|dangerous obstruction)/.test(text)) return 'urgent'; if (/(large|major|serious)/.test(text)) return 'high'; if (/(minor|small)/.test(text)) return 'low'; return 'moderate'; }
function extractLocation(message = '') { const match = message.trim().match(/(\d+\s+[\w\s]+(?:st|street|ave|avenue|blvd|road|rd|dr|lane|ln)\b|\b[\w\s]+\s+and\s+[\w\s]+\b)/i); return match ? match[1].trim() : null; }
function buildResponse({ issueType, severity, locationText }) { if (severity === 'emergency_referral') return 'STREETS received your message, but this may require emergency help. If anyone is in immediate danger, call 911 now. We have logged this for review.'; if (!locationText) return 'STREETS received your report. Please reply with the nearest address, intersection, or landmark.'; return `STREETS received your report. We logged it as ${issueType} with ${severity} priority. Reply STATUS for updates or ADD with more details.`; }
function parseInbound(payload = {}) { const mediaCount = Number(payload.NumMedia || 0); const media = []; for (let i = 0; i < mediaCount; i += 1) media.push({ url: payload[`MediaUrl${i}`], contentType: payload[`MediaContentType${i}`] }); return { from: payload.From || null, to: payload.To || null, body: payload.Body || '', messageSid: payload.MessageSid || null, media }; }
function safeNoopTwilio() { return !process.env.TWILIO_ACCOUNT_SID || !process.env.TWILIO_AUTH_TOKEN || (!process.env.TWILIO_MESSAGING_SERVICE_SID && !process.env.TWILIO_PHONE_NUMBER); }
module.exports = { hashPhone, classifyIssueType, classifySeverity, extractLocation, buildResponse, parseInbound, safeNoopTwilio };
